<a href="https://colab.research.google.com/github/Softwareguy786/Kaggle/blob/main/AirlinesSS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# IMPORTANT: SOME KAGGLE DATA SOURCES ARE PRIVATE
# RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES.
import kagglehub
kagglehub.login()

VBox(children=(HTML(value='<center> <img\nsrc=https://www.kaggle.com/static/images/site-logo.png\nalt=\'Kaggle…

In [2]:
# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.

playground_series_s6e10_path = kagglehub.competition_download('playground-series-s6e10')

print('Data source import complete.')

Data source import complete.

In [3]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

In [4]:
import os
print(playground_series_s6e10_path)
print(os.listdir(playground_series_s6e10_path))

/root/.cache/kagglehub/competitions/playground-series-s6e10
['test.csv', 'sample_submission.csv', 'train.csv']

In [5]:
import os, pandas as pd
base = playground_series_s6e10_path
train = pd.read_csv(os.path.join(base, 'train.csv'))
test  = pd.read_csv(os.path.join(base, 'test.csv'))
sub   = pd.read_csv(os.path.join(base, 'sample_submission.csv'))

In [6]:
print('TRAIN:',train.shape)

print('TEST:',test.shape)

TRAIN: (699635, 23)
TEST: (299844, 22)

In [7]:
train.sample(10)

,id,Age,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Gate location,Food and drink,Online boarding,Seat comfort,...,Baggage handling,Checkin service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,Gender,Customer Type,Type of Travel,Class,satisfaction
223746,223746,51,589,2,2,2,2,2,2,2,...,3,4,2,0,0.0,Male,Loyal Customer,Business travel,Eco,False
361703,361703,34,3841,2,2,3,3,1,4,3,...,2,3,3,0,0.0,Male,Loyal Customer,Business travel,Business,False
107992,107992,17,1709,2,2,2,2,2,2,2,...,3,3,2,0,0.0,Female,Loyal Customer,Business travel,Business,False
407332,407332,35,986,2,2,2,4,5,2,5,...,4,4,5,0,0.0,Female,disloyal Customer,Business travel,Eco,False
114838,114838,13,694,1,5,1,1,5,1,5,...,4,4,5,0,0.0,Male,Loyal Customer,Personal Travel,Eco,False
367578,367578,39,896,5,5,5,5,5,5,5,...,4,4,4,0,0.0,Male,Loyal Customer,Business travel,Business,True
321049,321049,33,372,1,4,4,4,1,1,1,...,4,3,1,0,0.0,Female,Loyal Customer,Business travel,Eco,False
356507,356507,35,1506,3,2,2,2,3,3,3,...,2,4,3,0,0.0,Male,Loyal Customer,Business travel,Eco Plus,False
693638,693638,33,2079,4,5,5,5,5,2,2,...,4,2,4,0,0.0,Female,Loyal Customer,Business travel,Business,False
530572,530572,50,888,4,3,3,3,5,3,4,...,4,2,1,37,12.0,Female,Loyal Customer,Business travel,Eco,True

In [8]:
train.dtypes

id                                     int64
Age                                    int64
Flight Distance                        int64
Inflight wifi service                  int64
Departure/Arrival time convenient      int64
Ease of Online booking                 int64
Gate location                          int64
Food and drink                         int64
Online boarding                        int64
Seat comfort                           int64
Inflight entertainment                 int64
On-board service                       int64
Leg room service                       int64
Baggage handling                       int64
Checkin service                        int64
Cleanliness                            int64
Departure Delay in Minutes             int64
Arrival Delay in Minutes             float64
Gender                                object
Customer Type                         object
Type of Travel                        object
Class                                 object
satisfaction                            bool
dtype: object

In [9]:
train.isna().sum()

id                                     0
Age                                    0
Flight Distance                        0
Inflight wifi service                  0
Departure/Arrival time convenient      0
Ease of Online booking                 0
Gate location                          0
Food and drink                         0
Online boarding                        0
Seat comfort                           0
Inflight entertainment                 0
On-board service                       0
Leg room service                       0
Baggage handling                       0
Checkin service                        0
Cleanliness                            0
Departure Delay in Minutes             0
Arrival Delay in Minutes             292
Gender                                 0
Customer Type                          0
Type of Travel                         0
Class                                  0
satisfaction                           0
dtype: int64

In [10]:
train['satisfaction'].value_counts()

satisfaction
False    389296
True     310339
Name: count, dtype: int64

In [11]:
train['satisfaction'].unique()

array([False,  True])

In [12]:
train.nunique().sort_values()

Type of Travel                            2
satisfaction                              2
Gender                                    2
Customer Type                             2
Class                                     3
Baggage handling                          5
Ease of Online booking                    6
Inflight wifi service                     6
On-board service                          6
Leg room service                          6
Checkin service                           6
Gate location                             6
Food and drink                            6
Inflight entertainment                    6
Online boarding                           6
Departure/Arrival time convenient         6
Seat comfort                              6
Cleanliness                               6
Age                                      75
Departure Delay in Minutes              167
Arrival Delay in Minutes                168
Flight Distance                        3474
id                                   699635
dtype: int64

In [13]:
test.isna().sum()

id                                     0
Age                                    0
Flight Distance                        0
Inflight wifi service                  0
Departure/Arrival time convenient      0
Ease of Online booking                 0
Gate location                          0
Food and drink                         0
Online boarding                        0
Seat comfort                           0
Inflight entertainment                 0
On-board service                       0
Leg room service                       0
Baggage handling                       0
Checkin service                        0
Cleanliness                            0
Departure Delay in Minutes             0
Arrival Delay in Minutes             130
Gender                                 0
Customer Type                          0
Type of Travel                         0
Class                                  0
dtype: int64

In [14]:
train['Arrival Delay in Minutes'] = train['Arrival Delay in Minutes'].fillna(train['Arrival Delay in Minutes'].median())

In [15]:
test['Arrival Delay in Minutes'] = test['Arrival Delay in Minutes'].fillna(test['Arrival Delay in Minutes'].median())

In [16]:
train.isna().sum()

id                                   0
Age                                  0
Flight Distance                      0
Inflight wifi service                0
Departure/Arrival time convenient    0
Ease of Online booking               0
Gate location                        0
Food and drink                       0
Online boarding                      0
Seat comfort                         0
Inflight entertainment               0
On-board service                     0
Leg room service                     0
Baggage handling                     0
Checkin service                      0
Cleanliness                          0
Departure Delay in Minutes           0
Arrival Delay in Minutes             0
Gender                               0
Customer Type                        0
Type of Travel                       0
Class                                0
satisfaction                         0
dtype: int64

In [17]:
train = pd.get_dummies(train, columns=['Gender','Customer Type','Type of Travel','Class'], drop_first=True)

In [18]:
test = pd.get_dummies(test, columns=['Gender','Customer Type','Type of Travel','Class'], drop_first=True)
test = test.drop(columns=['id'])

In [19]:
train['satisfaction'] = train['satisfaction'].astype(int)

In [25]:
train = train.drop(columns=['id'])

In [28]:
X = train.drop(columns=['satisfaction'])
X_test = test[X.columns]

In [22]:
X

,Age,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Gate location,Food and drink,Online boarding,Seat comfort,Inflight entertainment,...,Baggage handling,Checkin service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,Gender_Male,Customer Type_disloyal Customer,Type of Travel_Personal Travel,Class_Eco,Class_Eco Plus
0,36,694,4,4,4,3,1,4,1,1,...,4,3,1,0,0.0,False,False,True,True,False
1,56,651,5,5,5,5,5,4,4,5,...,5,4,3,0,0.0,True,False,False,False,False
2,31,1371,3,4,2,5,3,3,3,3,...,4,5,3,0,0.0,False,False,True,True,False
3,10,1616,3,5,3,3,3,3,3,3,...,3,4,3,0,0.0,True,False,True,True,False
4,23,481,3,4,3,4,5,3,5,5,...,5,3,5,5,0.0,False,True,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
699630,57,612,2,1,1,1,1,3,3,2,...,2,2,4,0,0.0,False,False,False,True,False
699631,30,862,2,2,2,3,4,2,4,4,...,4,2,4,24,34.0,False,True,False,True,False
699632,49,3148,5,5,5,5,4,4,4,5,...,5,5,5,0,0.0,True,False,False,False,False
699633,61,679,5,2,2,2,5,4,4,5,...,5,5,1,0,0.0,False,False,False,True,False
699634,42,813,1,1,0,4,3,0,3,3,...,3,4,3,0,0.0,True,False,True,True,False

In [30]:
X = train.drop(columns=['satisfaction'])
X_test = test[X.columns]

In [31]:
X, X_test = X.align(X_test, join='left', axis=1, fill_value=0)

In [33]:
X_test

,Age,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Gate location,Food and drink,Online boarding,Seat comfort,Inflight entertainment,...,Baggage handling,Checkin service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,Gender_Male,Customer Type_disloyal Customer,Type of Travel_Personal Travel,Class_Eco,Class_Eco Plus
0,25,1197,4,4,4,2,3,4,3,3,...,2,1,3,0,0.0,False,True,False,True,False
1,36,829,5,5,5,5,5,4,5,5,...,4,3,5,0,0.0,True,False,False,True,False
2,45,472,4,5,5,5,4,4,4,4,...,1,3,4,0,0.0,True,False,False,True,False
3,45,762,2,2,2,5,3,2,3,3,...,4,4,3,0,0.0,False,True,False,False,False
4,34,594,1,2,1,1,2,1,2,2,...,2,1,2,0,0.0,True,False,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299839,32,1725,3,1,3,3,3,3,3,3,...,3,1,3,0,0.0,False,False,False,False,False
299840,24,1325,3,3,3,4,3,3,3,2,...,3,5,3,0,0.0,False,True,False,True,False
299841,33,190,4,5,4,3,3,4,3,3,...,2,2,3,0,0.0,True,False,True,True,False
299842,59,678,3,5,3,2,4,3,5,5,...,4,4,5,4,0.0,True,False,True,True,False
299843,69,1044,2,5,2,2,4,2,4,4,...,3,1,4,0,0.0,True,False,True,True,False

In [34]:
print(X.shape, X_test.shape)
print(X.columns.equals(X_test.columns))

(699635, 22) (299844, 22)
True

In [35]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import roc_auc_score
import numpy as np