<a href="https://colab.research.google.com/github/Softwareguy786/Kaggle/blob/main/AirlinesSS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# IMPORTANT: SOME KAGGLE DATA SOURCES ARE PRIVATE
# RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES.
import kagglehub
kagglehub.login()

VBox(children=(HTML(value='<center> <img\nsrc=https://www.kaggle.com/static/images/site-logo.png\nalt=\'Kaggle…

Kaggle credentials set.
Kaggle credentials successfully validated.

In [3]:
# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.

playground_series_s6e10_path = kagglehub.competition_download('playground-series-s6e10')

print('Data source import complete.')

Downloading to /root/.cache/kagglehub/competitions/playground-series-s6e10.archive...

100%|██████████| 15.1M/15.1M [00:00<00:00, 16.3MB/s]

Extracting files...

Data source import complete.

In [4]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

In [7]:
import os
print(playground_series_s6e10_path)
print(os.listdir(playground_series_s6e10_path))

/root/.cache/kagglehub/competitions/playground-series-s6e10
['test.csv', 'sample_submission.csv', 'train.csv']

In [8]:
import os, pandas as pd
base = playground_series_s6e10_path
train = pd.read_csv(os.path.join(base, 'train.csv'))
test  = pd.read_csv(os.path.join(base, 'test.csv'))
sub   = pd.read_csv(os.path.join(base, 'sample_submission.csv'))

In [11]:
print('TRAIN:',train.shape)

print('TEST:',test.shape)

TRAIN: (699635, 23)
TEST: (299844, 22)

In [12]:
train.sample(10)

,id,Age,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Gate location,Food and drink,Online boarding,Seat comfort,...,Baggage handling,Checkin service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,Gender,Customer Type,Type of Travel,Class,satisfaction
167555,167555,62,1464,3,4,3,4,3,3,3,...,4,2,3,0,0.0,Male,Loyal Customer,Personal Travel,Eco,False
61760,61760,49,3162,2,1,1,1,5,3,3,...,3,5,2,0,0.0,Male,Loyal Customer,Business travel,Business,True
544183,544183,26,591,1,1,1,3,2,1,2,...,3,3,2,0,0.0,Female,disloyal Customer,Business travel,Eco,False
146852,146852,54,3918,1,1,1,1,2,4,4,...,4,5,4,0,0.0,Female,Loyal Customer,Business travel,Business,True
179901,179901,20,867,3,2,2,4,5,2,5,...,2,4,5,18,11.0,Male,disloyal Customer,Business travel,Eco,False
480918,480918,36,992,3,3,3,3,2,4,4,...,4,3,4,0,0.0,Male,Loyal Customer,Business travel,Business,True
278003,278003,66,1514,1,5,1,2,5,5,3,...,2,5,5,0,0.0,Female,Loyal Customer,Personal Travel,Eco,False
580385,580385,17,1056,4,5,5,3,4,5,4,...,2,3,4,0,0.0,Female,disloyal Customer,Business travel,Eco,True
271583,271583,11,862,3,5,3,3,2,3,2,...,5,3,2,0,0.0,Male,Loyal Customer,Personal Travel,Eco,False
294974,294974,48,1089,3,5,3,5,3,3,3,...,1,3,3,0,0.0,Male,Loyal Customer,Personal Travel,Eco,False

In [13]:
train.dtypes

id                                     int64
Age                                    int64
Flight Distance                        int64
Inflight wifi service                  int64
Departure/Arrival time convenient      int64
Ease of Online booking                 int64
Gate location                          int64
Food and drink                         int64
Online boarding                        int64
Seat comfort                           int64
Inflight entertainment                 int64
On-board service                       int64
Leg room service                       int64
Baggage handling                       int64
Checkin service                        int64
Cleanliness                            int64
Departure Delay in Minutes             int64
Arrival Delay in Minutes             float64
Gender                                object
Customer Type                         object
Type of Travel                        object
Class                                 object
satisfaction                            bool
dtype: object

In [14]:
train.isna().sum()

id                                     0
Age                                    0
Flight Distance                        0
Inflight wifi service                  0
Departure/Arrival time convenient      0
Ease of Online booking                 0
Gate location                          0
Food and drink                         0
Online boarding                        0
Seat comfort                           0
Inflight entertainment                 0
On-board service                       0
Leg room service                       0
Baggage handling                       0
Checkin service                        0
Cleanliness                            0
Departure Delay in Minutes             0
Arrival Delay in Minutes             292
Gender                                 0
Customer Type                          0
Type of Travel                         0
Class                                  0
satisfaction                           0
dtype: int64

In [16]:
train['satisfaction'].value_counts()

satisfaction
False    389296
True     310339
Name: count, dtype: int64

In [17]:
train['satisfaction'].unique()

array([False,  True])

In [18]:
train.nunique().sort_values()

Type of Travel                            2
satisfaction                              2
Gender                                    2
Customer Type                             2
Class                                     3
Baggage handling                          5
Ease of Online booking                    6
Inflight wifi service                     6
On-board service                          6
Leg room service                          6
Checkin service                           6
Gate location                             6
Food and drink                            6
Inflight entertainment                    6
Online boarding                           6
Departure/Arrival time convenient         6
Seat comfort                              6
Cleanliness                               6
Age                                      75
Departure Delay in Minutes              167
Arrival Delay in Minutes                168
Flight Distance                        3474
id                                   699635
dtype: int64